import {openCuriosity} from './messenger.mjs';
const CURIOSITY_BUTTON="<button type=\"button\" id=\"curiosity-button\" aria-haspopup=\"dialog\" title=\"채널톡으로 궁금증 물어보기\"><svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M20 11.5a8 8 0 0 1-8 8H4l1.6-4A8 8 0 1 1 20 11.5Z\"/><path d=\"M10 9a2 2 0 0 1 4 0c0 1.4-2 1.5-2 3\"/><path d=\"M12 15h.01\"/></svg>궁금증</button>";

function photoPreview(photo){return `<img src="${esc(photo.url)}" alt="${photo.variant==='sticker'?'배경을 지운 스티커 미리보기':'선택한 사진 미리보기'}"><span class="photo-pick-action">${icon('camera')}사진 바꾸기</span><span class="image-note">${photo.variant==='sticker'?'AI 누끼 결과':photo.sample?'합성 예시 사진':'선택한 사진'} · ${Math.round(photo.blob.size/1024)}KB</span>`;}
function cutoutControls(){const p=ui.photo;if(!p)return '';if(p.cutoutState==='running')return `<p id="cutout-status" class="cutout-status" role="status">${esc(p.cutoutStatus||'AI 도구를 불러오는 중…')}</p><button type="button" class="secondary" id="cutout-original" ${busy?'disabled':''}>취소하고 사진 그대로</button><p class="image-note">처음에는 약60MB의 AI 도구를 불러와요. 이름과 메모는 계속 적을 수 있어요.</p>`;if(p.stickerBlob)return `<div class="photo-variants" role="group" aria-label="저장할 사진 형태"><button type="button" id="cutout-original" ${busy?'disabled':''} aria-pressed="${p.variant==='original'}">사진 그대로</button><button type="button" id="cutout-sticker" ${busy?'disabled':''} aria-pressed="${p.variant==='sticker'}">스티커</button></div><p id="cutout-status" class="image-note" role="status">${p.variant==='sticker'?'배경을 지웠어요. 결과를 확인한 뒤 붙여 주세요.':'원래 사진으로 저장해요. 다시 스티커를 선택할 수도 있어요.'}</p>`;return `<button type="button" class="secondary" id="cutout-start" ${busy?'disabled':''}>${p.cutoutError?'다시 스티커로 만들기':'스티커로 만들기'}</button><p class="image-note">선택 사항 · 처음 약60MB의 AI 도구를 불러와요.<br>사진은 기기 안에서 처리하며, 스티커를 쓰면 축소 원본도 함께 보관해요.</p>${p.cutoutError?`<p class="error-note" role="alert">${esc(p.cutoutError)}</p>`:''}`;}
function updatePhotoControls(){const p=ui.photo,picker=main.querySelector('#photo-pick'),controls=main.querySelector('#cutout-controls');if(!p||!picker||!controls)return;const hadControlFocus=controls.contains(document.activeElement);picker.innerHTML=photoPreview(p);picker.classList.toggle('is-sticker',p.variant==='sticker');controls.innerHTML=cutoutControls();const submit=main.querySelector('#mission-form button[type="submit"]');if(submit)submit.disabled=busy||p.cutoutState==='running'||p.date!==(ui.trial?nextWeekday(state.today):state.today);bindCutout();if(hadControlFocus)(controls.querySelector('[aria-pressed="true"]')||controls.querySelector('button'))?.focus({preventScroll:true});}
function usePhotoVariant(variant){const p=ui.photo;if(!p||busy)return;cancelCutout();p.variant=variant==='sticker'&&p.stickerBlob?'sticker':'original';p.blob=p.variant==='sticker'?p.stickerBlob:p.originalBlob;p.url=p.variant==='sticker'?p.stickerUrl:p.originalUrl;p.cutoutError='';updatePhotoControls();main.querySelector(p.variant==='sticker'?'#cutout-sticker':'#cutout-original')?.focus({preventScroll:true});}
function bindCutout(){const start=main.querySelector('#cutout-start');if(start)start.onclick=runCutout;const original=main.querySelector('#cutout-original');if(original)original.onclick=()=>usePhotoVariant('original');const sticker=main.querySelector('#cutout-sticker');if(sticker)sticker.onclick=()=>usePhotoVariant('sticker');}
async function runCutout(){const p=ui.photo;if(!p||busy||cutoutJob)return;const token=++cutoutToken;p.cutoutState='running';p.cutoutError='';p.cutoutStatus='AI 도구를 불러오는 중…';updatePhotoControls();const job=startCutout(p.originalBlob,data=>{if(ui.photo!==p||token!==cutoutToken)return;const key=String(data.key||'');p.cutoutStatus=key.startsWith('fetch:')?`${key.includes('/models/')?'AI 모델':'실행 도구'} 불러오는 중 · ${(Number(data.current)/1048576).toFixed(1)} / ${(Number(data.total)/1048576).toFixed(1)}MB`:key==='crop'?'스티커 가장자리를 정리하는 중…':'기기 안에서 배경을 지우는 중…';const status=main.querySelector('#cutout-status');if(status)status.textContent=p.cutoutStatus;});cutoutJob=job;try{const result=await job.promise;if(ui.photo!==p||token!==cutoutToken)return;p.stickerBlob=result.blob;p.stickerUrl=URL.createObjectURL(result.blob);p.variant='sticker';p.blob=result.blob;p.url=p.stickerUrl;p.cutoutState='ready';notice('스티커를 만들었어요. 사진 그대로와 비교해 보세요.');}catch(error){if(ui.photo!==p||token!==cutoutToken)return;p.cutoutState='idle';if(error.name!=='AbortError'){p.cutoutError='배경을 지우지 못했어요. 사진 그대로 저장하거나 다시 시도해 주세요.';console.warn('Local cutout unavailable:',error.message);}}finally{if(cutoutJob===job)cutoutJob=null;if(ui.photo===p&&token===cutoutToken)updatePhotoControls();}}
import { REVEAL_FIELDS, SAMPLE_MEMBERS, todaySeoul, isWeekday, nextWeekday, addDays, weekDates, missionForDate, createState, validateState, revealedProfile, streak, reduce, memberCompleted } from './state.mjs';
import { loadState, saveState, getPhotoRecord, commitPhoto, resetStorage, compressPhoto, storageMessage } from './storage.mjs';
import { MAX_MESSAGE_LENGTH, photoForMember, roomMessages } from './room.mjs';
import { startCutout } from './cutout.mjs';

const main = document.querySelector('#main');
const preview = document.querySelector('#preview');
const sheet = document.querySelector('#sheet');
const toast = document.querySelector('#toast');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = {
  home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',
  book:'<path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-3-2H4Zm16 0h-4a3 3 0 0 0-3 3v14a4 4 0 0 1 3-2h4Z"/>',
  people:'<circle cx="8" cy="7" r="3"/><path d="M2 21v-4a6 6 0 0 1 12 0v4m2-17a3 3 0 0 1 0 6m1 4a5 5 0 0 1 5 5v2"/>',
  profile:'<circle cx="12" cy="7" r="4"/><path d="M3 21a9 9 0 0 1 18 0"/>',
  camera:'<path d="m8 5 1-2h6l1 2h5v15H3V5Z"/><circle cx="12" cy="12" r="4"/>',
  arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>',
  pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.book}</svg>`;
function friend(mood='normal',shape='crumpled') {
 const bodies={
  crumpled:'<path fill="#e7dcc1" d="M35 27 54 15 75 20 89 15 111 35 119 61 109 94 84 102 49 94 24 73 25 48Z"/><path stroke="#b1aa96" d="m35 27 24 19-8 30 33 26m-9-82-4 33 32 13 8-31M25 48l34-2 12 7-20 23m20-23 10 31 28 10M24 73l27 3 30 8 22-18"/>',
  folded:'<path fill="#efe6cd" d="m32 24 60-5 24 25-5 49-30 10-47-10-8-37Z"/><path fill="#d6c6a5" d="m92 19-3 27 27-2Z"/><path fill="#e0d3b7" stroke="none" d="m34 93 31-11 16 21Z"/><path stroke="#baad92" d="m32 24 20 23-18 46m18-46 13 35 46 11M89 46 65 82m27-63-3 27 27-2"/>',
  scrap:'<path fill="#e7e3d4" d="m29 29 11-6 13 6 13-8 16 6 14-6 18 10-2 25 7 15-8 23-17 3-13 7-13-6-17 3-18-10-8-24 7-16Z"/><path fill="#d4d0c1" stroke="none" d="m25 67 25 6 1 28-18-10Z"/><path fill="#f4efde" stroke="none" d="m82 27 14-6 18 10-26 9Z"/><path stroke="#b8b7a8" d="m40 23 10 28-25 16m25-16 20-8 18-3 8-19M50 51v22l31 31m-31-31 35-8 26 29M85 65l3-25 24 16"/>'
 };
 const label={crumpled:'꼬깃이',folded:'접힌 꼬깃이',scrap:'조각 꼬깃이'}[shape]||'꼬깃이';
 return `<button class="paper-friend" data-friend data-mood="${mood}" data-shape="${shape}" aria-label="${label} 톡 건드리기"><svg viewBox="0 0 150 140" aria-hidden="true">${bodies[shape]||bodies.crumpled}<path d="m48 94-3 22-13 3m52-17 11 17 14-2"/><path class="friend-arm-left" d="m34 59-18 2"/><path class="friend-arm-right" d="m116 65 17-8"/><path class="friend-open-eyes" d="${shape==='scrap'?'M60 59h7m17-3v5':'M63 56v5m24-5v5'}"/><path class="friend-sleep-eyes" d="m59 60 5 2 4-2m15 0 5 2 4-2"/><path d="m67 70 7 3 8-4"/><path stroke="#c18b72" d="M54 66h6m32-1h6"/></svg></button>`;
}
function mascot(text,mood='normal') { return `<aside class="mascot-note side-column">${friend(mood)}<p class="bubble">${text}</p><small class="tiny-label">꼬깃이 · 톡 건드려도 좋아.</small></aside>`; }
const pages=[['today','오늘','home'],['journal','도감','book'],['groups','옆자리','people'],['profile','내 소개','profile']];
let state=createState(todaySeoul());
let fatal='';
let busy=false;
let stale=false;
let toastTimer;
let registration='확인 중';
let photoUrls=new Map();
let cutoutJob=null,cutoutToken=0;
const ui={page:'today',step:1,draft:{campus:'자연과학캠퍼스'},editing:false,photo:null,memoryName:'',caption:'',error:'',trial:false,groupId:null,week:null,groupPanel:'photos',groupSettingsOpen:false,chatDrafts:new Map(),chatScroll:new Map(),chatErrors:new Map(),chatSending:false,chatJump:null};
function notice(text) { clearTimeout(toastTimer);toast.textContent=text;toastTimer=setTimeout(()=>{toast.textContent='';},5000); }
function heading(kicker,title,description,extra='') { return `<header class="page-heading"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1>${description?`<p>${esc(description)}</p>`:''}</div>${extra}</header>`; }
const dateText = date => new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'long'}).format(new Date(date+'T12:00:00+09:00'));
const sampleIndex = mission => ({음료:0,쉼터:1,색:2,기록:2,가방:3}[mission.theme] ?? 1);
const activeGroups = () => state.groups.filter(g=>g.status==='active'&&!g.left).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
const membersOf = group => group.activeMemberIds || group.memberIds;
function memberProfile(id){return id==='self'?state.profile:SAMPLE_MEMBERS.find(m=>m.id===id)?.profile;}
const footer = () => `<p class="footnote">기기 안에서만 쓰는 인터랙티브 데모예요. 옆자리의 다섯 명은 모두 가상 인물이고, 활동·이탈은 정해진 샘플입니다.<br>사이트 데이터를 지우거나 다른 기기로 옮기면 기록이 따라가지 않아요. 사진 속 타인의 얼굴·학번·연락처는 남기지 않는 편이 좋아요.</p>`;
function cancelCutout(){cutoutToken++;cutoutJob?.cancel();cutoutJob=null;if(ui.photo?.cutoutState==='running'){ui.photo.cutoutState='idle';ui.photo.cutoutStatus='';}}
function releasePhotoSelection(){cancelCutout();if(ui.photo)for(const url of new Set([ui.photo.url,ui.photo.originalUrl,ui.photo.stickerUrl].filter(Boolean)))URL.revokeObjectURL(url);}
function clearSelection(){releasePhotoSelection();ui.photo=null;ui.memoryName='';ui.caption='';ui.error='';}
function bindFriends(root){root.querySelectorAll('[data-friend]').forEach(b=>b.onclick=()=>notice(ui.trial?'체험은 체험으로. 네 도감은 그대로야.':isWeekday(state.today)?'잘한 하루 말고, 좋아한 하루면 돼.':'주말에는 꼬깃이도 조금 쉬어.'));}
function route(page){if(!pages.some(p=>p[0]===page))return;if(!state.profile)return;cancelCutout();ui.page=page;ui.editing=false;ui.error='';render();main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function setBanner(text){document.querySelector('#storage-banner').textContent=text;}
async function dispatch(action){if(fatal)throw new Error('기존 기록을 읽지 못해 변경할 수 없어요. 다시 읽거나 초기화 확인을 먼저 진행해 주세요.');if(stale)throw new Error('다른 탭에서 기록이 바뀌었어요. 새로고침한 뒤 이어가 주세요.');if(busy)throw new Error('먼저 진행 중인 작업이 끝날 때까지 기다려 주세요.');const next=reduce(state,action);if(next!==state){saveState(next);state=next;setBanner('');}return state;}
function onError(error){ui.error=error?.message==='nickname is required'?'별명을 한 글자 이상 적어주세요.':storageMessage(error);notice(ui.error);const el=document.querySelector('#form-error');if(el)el.textContent=ui.error;else setBanner(ui.error);}
function revealSequence(){return `<ol class="reveal-list">${REVEAL_FIELDS.map((f,i)=>`<li><span class="day">${i+1}일째</span>${f.label}</li>`).join('')}</ol>`;}

function onboarding(){
 const step=ui.step;
 let body='';
 if(step===1)body=`<div class="paper torn"><div class="step-counter">처음 펼치는 도감 · 1 / 3</div><div class="mascot-inline">${friend('happy')}<p>나, 꼬깃이.<br>네 학교가 조금 덜 낯설어지게<br>작은 조각들을 같이 모아볼까?</p></div><div class="wavy-divider"></div><p class="welcome-copy">친구를 먼저 만들 필요 없어.<br>내가 좋아한 것 하나부터.</p><ul class="info-list"><li>평일에 작은 미션을 하고 사진을 한 장 남겨요.</li><li>미션을 마치면 가상의 새 6인 조를 만나요.</li><li>유지한 조에서는 평일마다 소개가 하나씩 펼쳐져요.</li><li>이름 대신 데모 정보를 써도 괜찮아요. 가입이나 학교 인증은 없어요.</li></ul><button class="primary" data-action="setup-next">내 도감 펼치기 ${icon('arrow')}</button></div>`;
 if(step===2)body=`<form id="profile-form" class="paper fold"><div class="step-counter">나를 조금 소개해볼까 · 2 / 3</div><p class="caption" style="margin-bottom:22px">별명과 캠퍼스만 필수예요. 나머지는 비워도 되고, 가상의 정보를 써도 좋아요.</p><div class="form-grid">${profileFields()}</div><p id="form-error" class="error-note" role="alert">${esc(ui.error)}</p><div class="form-actions"><button type="button" class="text-link" data-action="setup-back">뒤로</button><button type="submit" class="primary">어떤 순서로 보일까? ${icon('arrow')}</button></div></form>`;
 if(step===3)body=`<form id="consent-form" class="paper torn"><div class="step-counter">천천히 펼치는 이야기 · 3 / 3</div><h2 class="welcome-copy">처음엔, 별명 ‘${esc(ui.draft.nickname)}’만.</h2><p class="caption">새 조는 1일째부터 시작해요. ‘다음 평일에도 함께’를 켠 조만 다음 평일에 한 단계씩 펼쳐져요. 주말은 세지 않아요.</p>${revealSequence()}<p class="privacy-note">지금은 실제 사람이 없는 시연이에요. 소개와 사진은 현재 브라우저에만 저장되고 누구에게도 전송되지 않아요. 공개 단계는 화면 연출이며, 실제 서비스의 보안 기능은 아닙니다.</p><label class="checks"><input id="consent" type="checkbox" required>기기 저장 방식과 공개 순서를 확인했어요.</label><p id="form-error" class="error-note" role="alert">${esc(ui.error)}</p><div class="form-actions"><button type="button" class="text-link" data-action="setup-back">소개 수정</button><button type="submit" class="primary">${ui.editing?'소개 저장하기':'스꾸깃 시작하기'}</button></div></form>`;
 return heading('skkugit · 성균관대학교 학생 프로젝트','스꾸깃, 작은 기억 수집실','조금 꼬깃해도, 나에게는 소중한 것들.')+`<div class="setup-layout"><div class="paper-wrap tape">${body}</div>${mascot('잘 적으려고<br>너무 애쓰진 마.<br>천천히 알아가면 되니까.','happy')}</div>`;
}
function profileFields(){const order=['nickname','campus','interests','hobbies','personality','frequentPlace','year','college','department','name'];const placeholders={nickname:'종이별',interests:'산책, 영화, 커피',hobbies:'그림 그리기',personality:'낯가리지만 잘 웃어요',frequentPlace:'학교 도서관',college:'단과대 이름',department:'학과 이름',name:'데모 이름도 좋아요'};return order.map(key=>{const label=REVEAL_FIELDS.find(f=>f.key===key).label;let control;if(key==='campus')control=`<select id="field-campus" name="campus" required>${['자연과학캠퍼스','인문사회과학캠퍼스'].map(x=>`<option ${ui.draft.campus===x?'selected':''}>${x}</option>`).join('')}</select>`;else if(key==='year')control=`<select id="field-year" name="year"><option value="">아직 적지 않을래요</option>${['1학년','2학년','3학년','4학년','기타'].map(x=>`<option ${ui.draft.year===x?'selected':''}>${x}</option>`).join('')}</select>`;else control=`<input id="field-${key}" name="${key}" value="${esc(ui.draft[key])}" maxlength="${key==='nickname'?20:key==='name'?40:80}" ${key==='nickname'?'required':''} placeholder="${placeholders[key]||''}" autocomplete="off">`;return `<div class="field"><label for="field-${key}">${label} ${!['nickname','campus'].includes(key)?'<span class="optional">선택</span>':'<span class="optional">필수</span>'}</label>${control}</div>`;}).join('');}

function todayPage(){
 const weekend=!isWeekday(state.today);
 if(weekend&&!ui.trial)return heading(dateText(state.today),'주말에는, 종이도 쉬어.','미션도 소개 공개도 잠깐 쉬는 날이야.')+`<div class="paper-wrap tape"><section class="paper torn weekend-card"><div><span class="hand-tag">토요일과 일요일은 쉬어가기</span><h2>오늘은 그냥,<br>좋아하는 곳에 있어도 돼.</h2><p>주말에는 새 조가 생기지 않고, 유지 일수도 늘지 않아요.<br>궁금하면 월요일을 먼저 체험해볼 수 있어요.</p><div class="form-actions"><button class="primary" data-action="trial-start">월요일 미션 미리 체험하기 ${icon('arrow')}</button><button class="text-link" data-route="journal">내 도감 구경하기</button></div><p class="image-note">체험 사진·조·연속 참여일은 실제 기록에 반영하지 않아요.</p></div>${friend('sleep')}</section></div><div class="wavy-divider"></div><div class="mascot-inline">${friend('sleep')}<p>빠진 날은 없어.<br>주말은 원래 비워두는 거야.</p></div>`;
 const date=ui.trial?nextWeekday(state.today):state.today;
 const mission=missionForDate(date,state.profile.campus);
 const entry=!ui.trial&&state.entries.find(e=>e.date===date);
 const canSave=ui.photo&&ui.photo.date===date&&!busy&&ui.photo.cutoutState!=='running';
 const body=entry?`<div class="paper fold"><div class="mascot-inline">${friend('happy')}<div><h2 class="welcome-copy">오늘의 조각은 잘 붙여뒀어.</h2><p class="caption">${esc(entry.memoryName||entry.title)}</p><p class="image-note">${esc(entry.groupName)}도 한 번만 만들어졌어요. 같은 날 다시 눌러도 늘어나지 않아요.</p></div></div><div class="form-actions"><button class="primary" data-entry="${esc(entry.id)}">오늘 기록 펼치기</button>${state.groups.some(g=>g.id===entry.groupId&&g.status==='active')?'<button class="secondary" data-action="show-today-group">오늘의 옆자리 보기</button>':'<span class="image-note">오늘의 조에서 나왔어요. 다음 평일에 새 조를 만나요.</span>'}</div></div>`:`<form id="mission-form" class="mission-form"><button type="button" id="photo-pick" class="photo-picker ${ui.photo?'has-photo':''} ${ui.photo?.variant==='sticker'?'is-sticker':''}" aria-label="${busy?'사진 준비 중':ui.photo?'사진 바꾸기':'사진 한 장 고르기'}" aria-describedby="photo-help" ${busy?'disabled aria-busy="true"':''}>${ui.photo?photoPreview(ui.photo):`${icon('camera')}<span class="photo-pick-title">${busy?'사진 준비 중':'사진 한 장 고르기'}</span><span class="photo-pick-hint">20MB 이하</span>`}</button><input id="photo-file" type="file" accept="image/*" hidden ${busy?'disabled':''}><p id="photo-help" class="image-note photo-help">사진 전송 없음 · 선택한 경우에만 기기 내 누끼 처리</p><div id="cutout-controls" class="cutout-controls">${cutoutControls()}</div>${ui.trial||state.demoDate?`<button class="secondary" type="button" data-action="sample-photo" ${busy?'disabled':''}>예시 조각으로 체험</button>`:''}<div class="form-grid memory-fields"><div class="field memory-card"><label for="memory-name">이 조각의 이름 <span class="optional">선택</span></label><input id="memory-name" maxlength="40" value="${esc(ui.memoryName)}" placeholder="예: 도서관 창가"></div><div class="field memory-card"><label for="memory-caption">이날의 이야기 <span class="optional">선택</span></label><textarea id="memory-caption" maxlength="200" placeholder="짧은 메모를 남겨보세요">${esc(ui.caption)}</textarea></div></div><p id="form-error" class="error-note" role="alert">${esc(ui.error)}</p>${ui.photo&&ui.photo.date!==date?'<p class="error-note">날짜가 바뀌었어요. 새 미션의 사진을 다시 선택해 주세요.</p>':''}<div class="form-actions"><button class="primary" type="submit" ${canSave?'':'disabled'}>${busy?'처리 중':ui.trial?'체험으로 붙여보기':'미션 완료 · 도감에 붙이기'}</button>${ui.trial?'<button class="text-link" type="button" data-action="trial-exit">주말로 돌아가기</button>':''}</div><p class="image-note">${ui.trial?'이 체험은 저장하지 않아요.':'저장하면 오늘의 새 6인 샘플 조가 열려요. 사진은 도감에 보관하며, 조 멤버에게 전송하지 않아요.'}</p></form>`;
 return heading(dateText(date)+(ui.trial?' · 월요일 체험':''),ui.trial?'월요일을 살짝 먼저 펼쳐볼까?':'오늘, 뭘 하나 주워볼까?','',`<span class="day-streak">${streak(state)?`${streak(state)}일 연속 · 평일 기준`:state.entries.length?'오늘도, 한 조각만':'첫 조각, 오늘부터'}</span>`)+(ui.trial?'<div class="trial-note">주말 미리 체험 · 사진과 조는 이 화면에서만 보여요. 실제 도감·조·연속 참여일은 바뀌지 않아요.</div>':'')+`<div class="mission-layout"><div><section class="story-paper"><div class="story-copy"><span class="hand-tag">오늘의 미션${entry?'':' · '+esc(mission.id)}</span><h2>${esc(entry?.title||mission.title)}</h2>${!entry?`<p class="caption">${esc(mission.prompt)}</p><p class="image-note">인증 예시 · ${esc(mission.proof)}</p>${mission.note?`<p class="image-note">${esc(mission.note)}</p>`:''}<details class="image-note"><summary>현재 데모의 기록 방식</summary><p>대표 사진 한 장과 메모를 저장해요. 여러 장의 사진·지도는 한 장으로 모아 첨부할 수 있어요. 인증 내용은 자동 심사하지 않아요.</p></details>`:''}</div><div class="keepsake-scene"><div class="photo ${['coffee','lake','path','book'][sampleIndex(mission)]}" role="img" aria-label="AI로 만든 수집물 예시"></div><span class="image-note scene-note">합성 예시</span></div></section>${body}</div><aside class="mascot-note side-column quiet-mascot">${friend(entry?'happy':'normal','folded')}</aside></div>`;
}

function journalPage(){const week=weekDates(ui.week||state.today);const currentWeek=weekDates(state.today)[0];return heading('나의 도감','별것 아닌 게, 내 것이 되는 곳.','주말은 비워둔, 평일 다섯 조각.')+`<div class="journal-opening"><div class="week-controls"><button data-week="prev" aria-label="이전 주">‹</button><strong>${week[0].slice(5).replace('-','.')} – ${week[4].slice(5).replace('-','.')}</strong><button data-week="next" aria-label="다음 주" ${week[0]>=currentWeek?'disabled':''}>›</button></div><span>${icon('lock')} 도감 사진은 나만 봐요</span></div><div class="week-grid">${week.map((date,i)=>{const e=state.entries.find(x=>x.date===date);return e?`<button class="week-slot" data-entry="${esc(e.id)}" aria-label="${esc(date+' '+(e.memoryName||e.title))}"><span class="weekday">${['월','화','수','목','금'][i]}<small>${date.slice(5).replace('-','.')}</small></span><img data-photo-id="${esc(e.photoId)}" alt="${esc(e.memoryName||e.title)}"><h2>${esc(e.memoryName||e.title)}</h2><span class="mission-small">${esc(e.title)}</span><span class="stamp">${esc(e.groupName)}</span></button>`:`<div class="week-slot empty-slot fold"><span class="weekday">${['월','화','수','목','금'][i]}<small>${date.slice(5).replace('-','.')}</small></span><p>${date>state.today?'아직 펼치지<br>않은 하루.':'이날은<br>비워뒀어.'}</p><span class="mission-small">채우는 숙제는 아니니까.</span></div>`;}).join('')}</div><div class="mascot-inline">${friend(state.entries.length?'happy':'normal','scrap')}<p>${state.entries.length?'한 장 한 장, 네 학교가 되는 중.':'처음 붙일 조각은 어떤 모양일까?'}<br>빠진 날이 있어도 괜찮아.</p></div>`;}

function groupsPage(){const groups=activeGroups();const completedToday=state.entries.some(e=>e.date===state.today);if(!groups.length)return heading('옆자리',state.groups.length?'옆자리가 잠깐 비어 있어.':'아직, 만나기 전이야.',completedToday?'오늘의 새 조는 이미 만났어요. 다음 평일 미션에서 다시 만나요.':'평일 미션을 마치면 오늘의 새 6인 샘플 조가 생겨요.')+`<div class="paper-wrap tape"><section class="paper torn"><div class="mascot-inline">${friend('normal')}<p>친구를 먼저 만들 필요 없어.<br>네 조각을 하나 남기고 와.</p></div><button class="primary" data-route="${completedToday?'journal':'today'}">${completedToday?'내 도감 보러 가기':'오늘의 핑계 보러 가기'} ${icon('arrow')}</button><p class="image-note">종료되거나 나간 조는 이 목록에 나오지 않아요. 내 도감의 당시 조 스탬프는 남아요.</p></section></div>`;
 const group=groups.find(g=>g.id===ui.groupId)||groups[0];ui.groupId=group.id;const ids=membersOf(group);const next=REVEAL_FIELDS[group.stage];
 return heading('사진 · 대화','옆자리','')+
 `<div class="group-tabs" aria-label="조 선택">${groups.map(g=>`<button class="group-tab" data-group="${esc(g.id)}" aria-pressed="${g.id===group.id}">${esc(g.name)} · ${g.daysTogether}일째</button>`).join('')}</div>
 <section class="paper fold group-summary"><div class="group-intro"><div><h2>${esc(group.name)}</h2><p>${ids.length}명 · 함께한 평일 ${group.daysTogether}일</p></div><span class="stamp">${group.createdAt.slice(5).replace('-','.')}에 처음 만남</span></div>
 <details class="group-settings" ${ui.groupSettingsOpen?'open':''}><summary><span>소개 공개 · 조 설정</span><span class="settings-state">${group.stage}/10단계 · 유지 ${group.keep?'켜짐':'꺼짐'}</span>${icon('arrow')}</summary><p class="image-note">${next?`다음 평일에는 ‘${next.label}’ 이야기가 펼쳐져요.`:'열 가지 소개를 모두 펼쳤어요.'}</p>
 <div class="reveal-strip" aria-label="공개 순서">${REVEAL_FIELDS.map((f,i)=>`<div class="reveal-step ${i<group.stage?'open':''} ${i===group.stage-1?'current':''}"><span>${i+1}</span>${f.label}</div>`).join('')}</div>
 <div class="group-actions"><div><label class="keep-switch"><input type="checkbox" role="switch" id="keep-group" aria-label="다음 평일에도 이 조와 함께" aria-describedby="keep-note" ${group.keep?'checked':''}><span class="keep-switch-art" aria-hidden="true"><span class="switch-on">켜짐</span><span class="switch-off">꺼짐</span><span class="keep-switch-thumb"></span></span><span>다음 평일에도 이 조와 함께</span></label><p id="keep-note" class="keep-note">${group.keep?(group.stage>=10?'다음 평일에도 함께해요. 열 가지 소개는 계속 펼쳐둬요.':'다음 평일에 유지 일수와 공개 단계가 올라가요.'):'꺼져 있어요. 다음 평일에 이 조는 종료돼요.'}<br>토·일요일은 세지 않아요. 새 미션 조는 별도로 생겨요.</p></div><button class="danger-link" data-action="leave-group">이 조 나가기</button></div></details></section>
 <div class="room-view-tabs" role="group" aria-label="옆자리 보기"><button data-group-panel="photos" aria-pressed="${ui.groupPanel==='photos'}" aria-controls="group-gallery">사진 ${ids.length}</button><button data-group-panel="chat" aria-pressed="${ui.groupPanel==='chat'}" aria-controls="room-chat">대화 ${roomMessages(group).length}</button></div>
 <div class="group-social-layout" data-panel="${ui.groupPanel}"><section class="group-gallery" id="group-gallery" aria-label="이 조의 사진"><div class="gallery-heading"><h2>각자의 조각</h2><span>사진은 크게 · 별명은 소개</span></div><div class="member-grid">${ids.map(id=>memberCard(id,group)).join('')}</div><p class="image-note">다른 멤버의 사진은 합성 예시예요. 내 도감 사진은 자동으로 대화에 공유되지 않아요.</p></section>${roomPane(group)}</div>
 <p class="privacy-note">유지한 조의 가상 멤버는 평일 4·7·10일째 5·3·2명이 되는 샘플 시나리오예요. 떠난 멤버를 새로 채우지는 않아요.</p>`;
}
function samplePicture(photo,label){return `<span class="sample-picture" data-sprite="${photo.sprite}" role="img" aria-label="${esc(label||photo.title)}"><img src="./assets/stickers.jpg" alt="" decoding="async"></span>`;}
function memberCard(id,group){
 const profile=memberProfile(id),visible=revealedProfile(profile,group.stage),shown=REVEAL_FIELDS.slice(Math.max(1,group.stage-2),group.stage),photo=photoForMember(group,id),entry=state.entries.find(e=>e.groupId===group.id);
 const visual=photo?samplePicture(photo,photo.title):entry?`<span class="own-picture"><img data-photo-id="${esc(entry.photoId)}" alt="${esc(entry.memoryName||entry.title)}"></span>`:'<span class="photo-missing">이 조의 사진 기록이 없어요.</span>';
 return `<article class="member-card fold"><button class="member-photo" data-room-photo="${esc(id)}" aria-label="${esc(profile.nickname)}의 ${photo?'샘플':'비공개'} 사진 크게 보기">${visual}<span class="photo-corner" aria-hidden="true">↗</span></button><div class="member-identity"><span class="paper-avatar" aria-hidden="true">${esc(Array.from(profile.nickname)[0])}</span><button class="member-name" data-member="${esc(id)}" aria-label="${esc(profile.nickname)}의 소개 보기"><span>${esc(visible.nickname)}</span><small>${id==='self'?'나 · 개인 도감':'샘플 멤버'} ${icon('arrow')}</small></button></div><p class="member-photo-name">${esc(photo?.title||entry?.memoryName||entry?.title||'내 기록')}</p>${shown.map(f=>`<p>${f.label} · ${esc(visible[f.key]||'아직 적지 않았어')}</p>`).join('')}${group.stage<10?`<p class="member-next">${icon('lock')} 다음 소개 · ${REVEAL_FIELDS[group.stage].label}</p>`:''}</article>`;
}
function roomDraft(groupId){if(!ui.chatDrafts.has(groupId))ui.chatDrafts.set(groupId,{text:'',photoMemberId:null});return ui.chatDrafts.get(groupId);}
function roomTime(time){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(time));}
function roomDate(time){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(time));}
function roomPane(group){
 const draft=roomDraft(group.id),messages=roomMessages(group),quoted=photoForMember(group,draft.photoMemberId);let previousDay='';
 const rows=messages.map(m=>{const mine=m.senderId==='self',profile=memberProfile(m.senderId),day=roomDate(m.time),divider=day!==previousDay?`<li class="chat-day"><span>${esc(dateText(day))}</span></li>`:'';previousDay=day;const photo=photoForMember(group,m.photoMemberId);return divider+`<li class="chat-row ${mine?'mine':'theirs'}" data-message-id="${esc(m.id)}">${mine?'':`<span class="chat-avatar" aria-hidden="true">${esc(Array.from(profile.nickname)[0])}</span>`}<div class="chat-message"><div class="chat-author">${mine?'나':esc(profile.nickname)}<span>${m.sample?'샘플':'기기 저장'}</span></div><div class="message-bubble">${photo?`<button class="message-photo" data-room-photo="${esc(m.photoMemberId)}" aria-label="${esc(memberProfile(m.photoMemberId).nickname)}의 인용 사진 크게 보기">${samplePicture(photo)}<span>${esc(memberProfile(m.photoMemberId).nickname)}의 사진 · ${esc(photo.title)}</span></button>`:''}${m.text?`<p class="message-text">${esc(m.text)}</p>`:''}</div><time class="message-time" datetime="${esc(m.time)}">${roomTime(m.time)}</time></div></li>`;}).join('');
 return `<section class="room-chat" id="room-chat" aria-labelledby="room-title"><header class="room-header"><div><span class="room-eyebrow">GROUP NOTE</span><h2 id="room-title">${esc(group.name)} 대화</h2></div><button class="sample-reply" id="sample-reply" title="미리 준비한 가상 멤버 답장 추가" ${ui.chatSending||busy?'disabled':''}>샘플 답장</button></header><p class="room-notice">가상 대화 · 내 글은 이 기기에만 저장돼요.</p><ol class="room-messages" id="room-messages" data-group-id="${esc(group.id)}" tabindex="0" aria-label="${esc(group.name)} 메시지">${rows||'<li class="chat-empty">아직 대화가 없어요.</li>'}</ol><form class="room-compose" id="room-compose" data-group-id="${esc(group.id)}">${quoted?`<div class="compose-quote">${samplePicture(quoted)}<span><strong>${esc(memberProfile(draft.photoMemberId).nickname)}의 사진에 답장</strong><span>${esc(quoted.title)}</span></span><button type="button" id="quote-cancel" aria-label="사진 인용 취소">×</button></div>`:''}<label class="sr-only" for="room-draft">${esc(group.name)}에 남길 메시지</label><textarea id="room-draft" rows="2" maxlength="${MAX_MESSAGE_LENGTH}" placeholder="이 조에 남길 이야기" aria-describedby="room-error" ${ui.chatSending||busy?'disabled':''}>${esc(draft.text)}</textarea><div class="compose-actions"><span class="compose-hint">Enter는 줄바꿈</span><span class="message-count" id="message-count">${draft.text.length}/${MAX_MESSAGE_LENGTH}</span><button type="submit" class="primary" id="room-send" ${ui.chatSending||busy||(!draft.text.trim()&&!quoted)?'disabled':''}>${ui.chatSending?'저장 중':'보내기'} ${icon('arrow')}</button></div><p class="room-error" id="room-error" role="alert">${esc(ui.chatErrors.get(group.id)||'')}</p></form></section>`;
}
function openRoomPhoto(id){
 const group=state.groups.find(g=>g.id===ui.groupId);if(!group||!group.memberIds.includes(id))return;if(id==='self'){const entry=state.entries.find(e=>e.groupId===group.id);if(entry)openEntry(entry.id);return;}
 const photo=photoForMember(group,id);if(!photo)return;const profile=memberProfile(id);
 openSheet(`${profile.nickname}의 조각`,`<div class="room-photo-view">${samplePicture(photo,`${profile.nickname}의 사진 · ${photo.title}`)}</div><h3>${esc(photo.title)}</h3><p>${esc(photo.caption)}</p><p class="image-note">${esc(group.name)} · ${esc(dateText(group.createdAt))}<br>합성 사진과 가상 인물로 구성한 예시입니다.</p><button class="primary photo-reply" id="photo-reply">이 사진에 답장 ${icon('arrow')}</button>`);
 document.querySelector('#photo-reply').onclick=()=>{roomDraft(group.id).photoMemberId=id;ui.groupId=group.id;ui.groupPanel='chat';ui.chatJump=group.id;closeSheet();render();const input=document.querySelector('#room-draft');input?.focus({preventScroll:true});input?.scrollIntoView({block:'nearest'});};
}
async function sendRoomMessage(groupId,sample=false){
 if(ui.chatSending||busy)return;const draft=roomDraft(groupId),text=draft.text,photoMemberId=draft.photoMemberId;ui.chatSending=true;ui.chatErrors.delete(groupId);render();
 try{if(!state.demoDate)await checkClock();const current=state.groups.find(g=>g.id===groupId);if(!current||current.status!=='active')throw new Error('종료된 조에는 새 대화를 남길 수 없어요.');const sentAt=new Date(`${state.today}T${new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date())}+09:00`).toISOString();await dispatch({type:sample?'ADD_SAMPLE_REPLY':'SEND_GROUP_MESSAGE',groupId,id:'m-'+crypto.randomUUID(),text,photoMemberId,sentAt});if(!sample&&draft.text===text&&draft.photoMemberId===photoMemberId)ui.chatDrafts.set(groupId,{text:'',photoMemberId:null});ui.chatJump=groupId;notice(sample?'미리 준비한 샘플 답장을 추가했어요.':'이 조의 대화를 기기에 저장했어요. 실제 전송은 없어요.');}
 catch(error){ui.chatErrors.set(groupId,error.message==='room message cap reached'?'한 조에 보관할 수 있는 데모 메시지는 200개까지예요. 작성한 글은 그대로 남아 있어요.':storageMessage(error));}
 finally{ui.chatSending=false;render();if(ui.groupId===groupId){const target=document.querySelector(sample?'#sample-reply':'#room-draft');target?.focus({preventScroll:true});}}
}
function profilePage(){return heading('내 소개','천천히 알려줘도 괜찮아.','모든 소개는 이 브라우저에만 보관해요.')+`<div class="setup-layout"><section class="paper fold"><div class="mascot-inline">${friend('happy')}<p>안녕, ${esc(state.profile.nickname)}.<br>이름보다 먼저,<br>좋아하는 것부터 알면 되지.</p></div><dl class="sheet-details">${REVEAL_FIELDS.map(f=>`<div><dt>${f.label}</dt><dd>${esc(state.profile[f.key]||'아직 적지 않았어')}</dd></div>`).join('')}</dl><button class="primary" data-action="edit-profile">내 소개 수정하기</button><p class="image-note">수정한 소개는 기존 가상 조에서도 현재 공개 단계에 맞춰 표시됩니다.</p></section>${mascot('정답 같은<br>자기소개는 없어.<br>별명 하나면 시작이야.')}</div>`;}

function render(){
 const previousLog=main.querySelector('#room-messages');if(previousLog?.clientHeight)ui.chatScroll.set(previousLog.dataset.groupId,previousLog.scrollTop);
 document.querySelector('#navigation').innerHTML=pages.map(([key,label,ic])=>`<button data-route="${key}" ${state.profile?'':'disabled'} ${ui.page===key?'aria-current="page" class="active"':''}>${icon(ic)}${label}</button>`).join('')+CURIOSITY_BUTTON;
 document.querySelector('#sidebar-profile').innerHTML=`<span class="avatar">나</span><div>${esc(state.profile?.nickname||'아직 펼치기 전')}<small>기기 저장 · 가상 조 데모</small></div>`;
 document.querySelector('#campus-label').innerHTML=icon('pin')+esc(state.profile?.campus||'성균관대학교 학생 프로젝트');
 document.querySelector('#clock-label').innerHTML=`${state.demoDate?'<span class="demo-chip">데모 날짜</span> ':''}${state.today}`;
 let content;
 if(fatal)content=heading('기기 보관함','기록을 안전하게 읽지 못했어요.','기존 데이터는 자동으로 지우지 않았어요.')+`<div class="paper fold"><p class="error-note">${esc(fatal)}</p><p class="caption">데모 메뉴에서 ‘처음부터 다시 시작’을 선택하면 이 브라우저의 기록을 지우고 다시 시작할 수 있어요.</p><button class="secondary" data-action="reload">다시 읽기</button></div>`;
 else if(!state.profile||ui.editing)content=onboarding();
 else content=({today:todayPage,journal:journalPage,groups:groupsPage,profile:profilePage}[ui.page]||todayPage)();
 main.innerHTML=content+footer();main.classList.remove('page-enter');void main.offsetWidth;main.classList.add('page-enter');
 bind();hydrateImages(main);
 const log=main.querySelector('#room-messages');if(log)log.scrollTop=ui.chatJump===log.dataset.groupId||!ui.chatScroll.has(log.dataset.groupId)?log.scrollHeight:ui.chatScroll.get(log.dataset.groupId);ui.chatJump=null;
}
async function hydrateImages(root){for(const image of root.querySelectorAll('.sample-picture>img')){const missing=()=>{if(!image.isConnected)return;const frame=image.parentElement;frame.textContent='샘플 사진을 불러오지 못했어요.';frame.classList.add('photo-unavailable');frame.setAttribute('aria-label','샘플 사진을 불러오지 못했어요.');};image.onerror=missing;if(image.complete&&!image.naturalWidth)missing();}for(const img of root.querySelectorAll('img[data-photo-id]')){const id=img.dataset.photoId;try{let cached=photoUrls.get(id);if(!cached){const record=await getPhotoRecord(id);if(!record)throw new Error('사진이 없어요.');if(!img.isConnected)continue;cached=photoUrls.get(id);if(!cached){const originalUrl=URL.createObjectURL(record.originalBlob);cached={originalUrl,url:record.stickerBlob?URL.createObjectURL(record.stickerBlob):originalUrl,sticker:!!record.stickerBlob};photoUrls.set(id,cached);}}if(!img.isConnected)continue;img.src=cached.url;img.classList.toggle('is-sticker',cached.sticker);if(img.classList.contains('sheet-photo')){const body=img.closest('.sheet-body'),toggle=body.querySelector('[data-photo-toggle]'),note=body.querySelector('[data-photo-method]');if(note&&cached.sticker)note.textContent=(id.startsWith('sample-')?'합성 예시 사진을':'선택한 사진을')+' 기기 안에서 실제 AI로 배경 제거한 결과입니다. 원래 사진은 축소본으로 함께 보관했어요.';if(toggle){toggle.hidden=!cached.sticker;toggle.onclick=()=>{const original=img.dataset.variant!=='original';img.dataset.variant=original?'original':'sticker';img.src=original?cached.originalUrl:cached.url;img.classList.toggle('is-sticker',!original);toggle.textContent=original?'스티커 보기':'원래 사진 보기';};}}}catch(error){if(img.isConnected){const msg=document.createElement('p');msg.className='photo-missing';msg.textContent='사진을 불러오지 못했어요. 기록 정보는 남아 있어요.';img.replaceWith(msg);}}}}
function openSheet(title,body){document.querySelector('#sheet-title').textContent=title;document.querySelector('#sheet-content').innerHTML=`<div class="sheet-body">${body}</div>`;if(!sheet.open)sheet.showModal();else document.querySelector('#sheet-close').focus();bindFriends(sheet);hydrateImages(sheet);}
function closeSheet(){sheet.close();}
function openEntry(id){const entry=state.entries.find(e=>e.id===id);if(!entry)return;openSheet('그날의 조각',`<img class="sheet-photo" data-photo-id="${esc(entry.photoId)}" alt="${esc(entry.memoryName||entry.title)}"><button class="secondary original-photo-toggle" type="button" data-photo-toggle hidden>원래 사진 보기</button><h3>${esc(entry.memoryName||entry.title)}</h3>${entry.caption?`<p>${esc(entry.caption)}</p>`:''}<div class="wavy-divider"></div><p>${esc(dateText(entry.date))}<br>오늘의 핑계 · ${esc(entry.title)}</p><p style="margin-top:13px"><span class="stamp">당시 만난 ${esc(entry.groupName)}</span></p><p class="image-note" data-photo-method>${entry.photoId.startsWith('sample-')?'미리 만든 합성 예시를 저장한 데모 기록입니다.':'기기에서 축소·압축한 사진입니다. 자동 누끼 결과가 아닙니다.'}</p>`);}
function openMember(id){const group=state.groups.find(g=>g.id===ui.groupId);if(!group||!membersOf(group).includes(id))return;const profile=memberProfile(id),visible=revealedProfile(profile,group.stage);openSheet(`${profile.nickname}의 접힌 소개`,`${friend()}<p>${id==='self'?'내 소개':'가상 멤버'} · 이 조에서는 ${group.stage}단계까지 펼쳤어요.</p><dl class="sheet-details">${REVEAL_FIELDS.map((f,i)=>`<div><dt>${f.label}</dt><dd ${i>=group.stage?'class="locked"':''}>${i<group.stage?esc(visible[f.key]||'아직 적지 않았어'):`평일 ${i+1-group.stage}일 더 함께하면 펼쳐져요`}</dd></div>`).join('')}</dl><p class="image-note">공개 순서를 체험하는 데모입니다. 실제 다른 사용자의 정보가 아닙니다.</p>`);}
async function selectPhoto(file,sample=false){if(busy)return;cancelCutout();busy=true;ui.error='';notice('사진을 기기 안에서 줄이고 있어요.');render();try{const result=await compressPhoto(file);releasePhotoSelection();const originalUrl=URL.createObjectURL(result.blob);ui.photo={...result,originalBlob:result.blob,originalUrl,url:originalUrl,stickerBlob:null,stickerUrl:null,variant:'original',cutoutState:'idle',date:ui.trial?nextWeekday(state.today):state.today,sample};notice('사진 준비 완료. 이름과 이야기는 비워도 좋아요.');}catch(error){onError(error);}finally{busy=false;const focusId=document.activeElement.id;render();document.getElementById(focusId||'photo-pick')?.focus({preventScroll:true});}}
async function samplePhoto(){try{const response=await fetch('./assets/stickers.jpg');if(!response.ok)throw new Error('예시 조각을 불러오지 못했어요.');const bitmap=await createImageBitmap(await response.blob());const canvas=document.createElement('canvas');canvas.width=550;canvas.height=550;const date=ui.trial?nextWeekday(state.today):state.today;const n=sampleIndex(missionForDate(date,state.profile.campus));canvas.getContext('2d').drawImage(bitmap,(n%2)*bitmap.width/2,Math.floor(n/2)*bitmap.height/2,bitmap.width/2,bitmap.height/2,0,0,550,550);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.8));await selectPhoto(blob,true);}catch(error){onError(error);}}
async function complete(){if(busy||!ui.photo||ui.photo.cutoutState==='running')return;if(!state.demoDate&&todaySeoul()!==state.today){await checkClock();if(todaySeoul()!==state.today){onError(new Error('오늘 날짜를 갱신하지 못했어요. 새로고침한 뒤 다시 시도해 주세요.'));return;}}if(stale){onError(new Error('다른 탭에서 기록이 바뀌었어요. 새로고침한 뒤 이어가 주세요.'));return;}const target=ui.trial?nextWeekday(state.today):state.today;if(ui.photo.date!==target){onError(new Error('날짜가 바뀌었어요. 사진을 다시 선택해 주세요.'));return;}
 if(ui.trial){const sandbox=reduce(reduce(createState(target),{type:'SET_PROFILE',profile:state.profile}),{type:'COMPLETE_MISSION',photoId:'trial-only',memoryName:ui.memoryName,caption:ui.caption});const g=sandbox.groups[0];openSheet('월요일, 이렇게 만나게 돼요',`<div class="mascot-inline">${friend('happy')}<p>체험으로 한 조각 붙였어.<br>진짜 도감에는 남기지 않았어.</p></div><p class="privacy-note">월요일 미리 체험 완료. 실제 날짜·도감·조·연속 참여일은 그대로입니다.</p><div class="member-grid">${g.memberIds.map(id=>`<div class="member-card"><span class="paper-avatar">${esc(memberProfile(id).nickname[0])}</span><h3>${esc(memberProfile(id).nickname)}</h3><span class="who">${id==='self'?'나':'가상 멤버'}</span></div>`).join('')}</div><button class="primary" id="trial-done">주말로 돌아가기</button>`);document.querySelector('#trial-done').onclick=()=>{closeSheet();ui.trial=false;clearSelection();render();};return;}
 if(state.entries.some(e=>e.date===state.today)){notice('오늘의 조각과 조는 이미 만들어졌어요.');render();return;}
 const id=(ui.photo.sample?'sample-':'photo-')+crypto.randomUUID();let next;
 try{next=reduce(state,{type:'COMPLETE_MISSION',photoId:id,memoryName:ui.memoryName,caption:ui.caption});}catch(error){onError(error);return;}
 busy=true;render();try{await commitPhoto(next,id,{version:2,originalBlob:ui.photo.originalBlob,stickerBlob:ui.photo.variant==='sticker'?ui.photo.stickerBlob:null});state=next;const entry=state.entries.find(e=>e.date===state.today);ui.groupId=entry.groupId;ui.page='groups';ui.week=state.today;clearSelection();notice('도감에 붙였어요. 오늘의 새 6인 샘플 조도 펼쳤어요.');}catch(error){onError(error);}finally{busy=false;render();}}
function bind(){
 const curiosity=document.querySelector('#curiosity-button');
 if(curiosity)curiosity.onclick=async()=>{
   curiosity.disabled=true;curiosity.setAttribute('aria-busy','true');
   notice('채널톡을 여는 중이에요.');
   try{await openCuriosity();notice('');}
   catch(error){notice(error.message||'채널톡을 열지 못했어요. 잠시 후 다시 눌러 주세요. 도감 입력은 그대로예요.');}
   finally{curiosity.disabled=false;curiosity.removeAttribute('aria-busy');if(document.activeElement===document.body)curiosity.focus({preventScroll:true});}
 };

 bindCutout();
 document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));bindFriends(main);
 main.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>openEntry(b.dataset.entry));
 main.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{ui.groupId=b.dataset.group;render();});
 main.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>openMember(b.dataset.member));
 main.querySelectorAll('[data-room-photo]').forEach(b=>b.onclick=()=>openRoomPhoto(b.dataset.roomPhoto));
 main.querySelectorAll('[data-group-panel]').forEach(b=>b.onclick=()=>{ui.groupPanel=b.dataset.groupPanel;render();main.querySelector('[data-group-panel="'+ui.groupPanel+'"]')?.focus({preventScroll:true});});
 const settings=main.querySelector('.group-settings');if(settings)settings.ontoggle=()=>{if(settings.isConnected)ui.groupSettingsOpen=settings.open;};
 const chatForm=main.querySelector('#room-compose');if(chatForm){const groupId=chatForm.dataset.groupId,input=main.querySelector('#room-draft'),draft=roomDraft(groupId);input.oninput=()=>{draft.text=input.value;main.querySelector('#message-count').textContent=input.value.length+'/'+MAX_MESSAGE_LENGTH;main.querySelector('#room-send').disabled=ui.chatSending||busy||(!input.value.trim()&&!draft.photoMemberId);ui.chatErrors.delete(groupId);main.querySelector('#room-error').textContent='';};chatForm.onsubmit=e=>{e.preventDefault();sendRoomMessage(groupId);};main.querySelector('#sample-reply').onclick=()=>sendRoomMessage(groupId,true);const cancel=main.querySelector('#quote-cancel');if(cancel)cancel.onclick=()=>{draft.photoMemberId=null;render();main.querySelector('#room-draft')?.focus({preventScroll:true});};}
 main.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{ui.week=addDays(weekDates(ui.week||state.today)[0],b.dataset.week==='prev'?-7:7);render();});
 main.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
 const profileForm=main.querySelector('#profile-form');if(profileForm){profileForm.oninput=()=>ui.draft=Object.fromEntries(new FormData(profileForm));profileForm.onchange=profileForm.oninput;profileForm.onsubmit=e=>{e.preventDefault();ui.draft=Object.fromEntries(new FormData(profileForm));try{reduce(state,{type:'SET_PROFILE',profile:ui.draft});ui.step=3;ui.error='';render();}catch(error){onError(error);}};}
 const consent=main.querySelector('#consent-form');if(consent)consent.onsubmit=async e=>{e.preventDefault();if(!main.querySelector('#consent').checked)return;try{await dispatch({type:'SET_PROFILE',profile:ui.draft});ui.editing=false;ui.page='today';ui.step=1;ui.error='';render();notice('반가워요. 내 기기에 도감을 펼쳤어요.');}catch(error){onError(error);}};
 const file=main.querySelector('#photo-file');if(file){file.onchange=()=>{if(file.files[0])selectPhoto(file.files[0]);};main.querySelector('#photo-pick').onclick=()=>file.click();}
 const name=main.querySelector('#memory-name');if(name)name.oninput=()=>ui.memoryName=name.value;
 const caption=main.querySelector('#memory-caption');if(caption)caption.oninput=()=>ui.caption=caption.value;
 const mission=main.querySelector('#mission-form');if(mission)mission.onsubmit=e=>{e.preventDefault();complete();};
 const keep=main.querySelector('#keep-group');if(keep)keep.onchange=async()=>{const requested=keep.checked;try{await dispatch({type:'SET_KEEP',groupId:ui.groupId,keep:requested});notice(requested?'다음 평일에도 이 조와 함께할게요.':'다음 평일에 이 조를 종료할게요.');}catch(error){onError(error);}finally{render();main.querySelector('#keep-group')?.focus({preventScroll:true});}};
}
async function action(name){
 if(name==='setup-next'){ui.step++;render();}
 if(name==='setup-back'){ui.step=Math.max(1,ui.step-1);ui.error='';render();}
 if(name==='edit-profile'){ui.editing=true;ui.step=2;ui.draft={...state.profile};render();}
 if(name==='trial-start'){ui.trial=true;clearSelection();render();}
 if(name==='trial-exit'){ui.trial=false;clearSelection();render();}
 if(name==='sample-photo')await samplePhoto();
 if(name==='show-today-group'){const e=state.entries.find(x=>x.date===state.today);if(e)ui.groupId=e.groupId;route('groups');}
 if(name==='leave-group')confirmLeave();
 if(name==='reload')location.reload();
}
function confirmLeave(){const group=state.groups.find(g=>g.id===ui.groupId);if(!group)return;openSheet('이 조를 나갈까요?',`<div class="mascot-inline">${friend()}<p>${esc(group.name)}는<br>활성 목록에서 바로 사라져요.</p></div><p class="dialog-warning">내 사진과 당시 조 스탬프는 도감에 남아요. 이 샘플 조로 다시 돌아오지는 못해요.</p><div class="form-actions"><button class="secondary" id="confirm-cancel">조금 더 있을래요</button><button class="primary" id="confirm-leave">이 조 나가기</button></div><p id="dialog-error" class="error-note" role="alert"></p>`);document.querySelector('#confirm-cancel').onclick=closeSheet;document.querySelector('#confirm-leave').onclick=async()=>{try{await dispatch({type:'LEAVE_GROUP',groupId:group.id});closeSheet();ui.groupId=null;render();notice('이 조를 나왔어요. 내 도감은 그대로예요.');}catch(error){document.querySelector('#dialog-error').textContent=storageMessage(error);}};}
async function advanceDay(){if(ui.trial){ui.trial=false;clearSelection();}const date=nextWeekday(state.today);await dispatch({type:'ADVANCE_DATE',date,demo:true});ui.week=date;ui.page='today';ui.error='';clearSelection();render();notice(`${date} 데모 날짜로 넘어왔어요. 실제 매칭은 없어요.`);return summary();}
function demoMenu(){openSheet('작은 데모 서랍',`<p>현재 ${state.demoDate?'데모 날짜':'한국 실제 날짜'} · <strong>${state.today}</strong></p><p class="image-note">날짜를 넘기면 조 유지와 소개 공개도 함께 진행돼요. 이 데모 날짜는 새로고침 후에도 유지돼요. 실제 날짜로 시작하려면 초기화해 주세요.</p><div class="demo-options"><button class="secondary" id="advance-day" ${fatal?'disabled':''}>다음 평일로 이동 ${icon('arrow')}</button><label for="screen-width">화면 크기<select id="screen-width"><option value="">자동</option><option value="320">320px</option><option value="390">390px</option><option value="430">430px</option></select></label><label class="checks"><input id="large-text" type="checkbox" ${preview.classList.contains('large-text')?'checked':''}>글자 200% 미리보기</label><div class="wavy-divider"></div><button class="danger-link" id="reset-open">처음부터 다시 시작</button></div><p class="image-note">WebMCP: ${esc(registration)}. UI와 같은 상태 로직을 쓰며 사진·소개 값은 도구에 노출하지 않아요.</p><p id="dialog-error" class="error-note" role="alert"></p>`);const select=document.querySelector('#screen-width');select.value=preview.dataset.width||'';select.onchange=()=>{preview.dataset.width=select.value;preview.classList.toggle('compact',!!select.value);preview.style.maxWidth=select.value?select.value+'px':'';preview.style.setProperty('--preview-width',select.value?select.value+'px':'100%');document.documentElement.style.setProperty('--demo-width',select.value?select.value+'px':'100vw');closeSheet();};document.querySelector('#large-text').onchange=e=>{preview.classList.toggle('large-text',e.target.checked);document.documentElement.style.setProperty('--type-scale',e.target.checked?'2':'1');closeSheet();};document.querySelector('#advance-day').onclick=async()=>{try{await advanceDay();closeSheet();}catch(error){document.querySelector('#dialog-error').textContent=storageMessage(error);}};document.querySelector('#reset-open').onclick=confirmReset;}
function confirmReset(){openSheet('도감을 처음부터 펼칠까요?',`<p class="dialog-warning">이 브라우저에 저장한 모든 사진과 소개, 샘플 조와 대화를 지워요. 되돌릴 수 없어요.</p><p>다른 기기나 실제 학교 계정에는 영향을 주지 않아요.</p><div class="form-actions"><button class="secondary" id="reset-cancel">그대로 둘래요</button><button class="primary" id="reset-confirm">모두 지우고 다시 시작</button></div><p id="dialog-error" class="error-note" role="alert"></p>`);document.querySelector('#reset-cancel').onclick=closeSheet;document.querySelector('#reset-confirm').onclick=async()=>{if(busy)return;busy=true;document.querySelector('#reset-confirm').disabled=true;try{await resetStorage();state=createState(todaySeoul());fatal='';stale=false;setBanner('');ui.page='today';ui.step=1;ui.editing=false;ui.draft={campus:'자연과학캠퍼스'};ui.trial=false;ui.groupId=null;ui.week=null;ui.groupPanel='photos';ui.groupSettingsOpen=false;ui.chatDrafts.clear();ui.chatErrors.clear();ui.chatScroll.clear();clearSelection();for(const cached of photoUrls.values())for(const url of new Set([cached.url,cached.originalUrl]))URL.revokeObjectURL(url);photoUrls.clear();closeSheet();render();notice('이 브라우저의 도감을 비웠어요. 새 종이부터 시작해요.');}catch(error){document.querySelector('#dialog-error').textContent=storageMessage(error);document.querySelector('#reset-confirm').disabled=false;}finally{busy=false;}};}
function summary(){return {app:'skkugit',mode:'local-demo',page:ui.page,date:state.today,demoClock:!!state.demoDate,onboarded:!!state.profile,stateReadable:!fatal,needsReload:stale,entryCount:fatal?null:state.entries.length,groups:fatal?null:activeGroups().map(g=>({id:g.id,stage:g.stage,daysTogether:g.daysTogether,members:membersOf(g).length,keep:g.keep})),containsPersonalValues:false};}
async function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool){registration='이 브라우저에서 미지원 · 기본 UI는 정상 작동';return;}
 const tools=[{name:'skkugit_get_state',description:'Read only counts, demo date and reveal stages. Does not expose photos or profile values.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>JSON.stringify(summary())},{name:'skkugit_navigate',description:'Navigate the local skkugit demo to a main screen. Does not submit forms.',inputSchema:{type:'object',properties:{page:{type:'string',enum:pages.map(p=>p[0])}},required:['page'],additionalProperties:false},execute:async({page})=>{if(!pages.some(p=>p[0]===page))throw new Error('Invalid page');route(page);return JSON.stringify(summary());}},{name:'skkugit_next_weekday',description:'Advance the local demo clock to the next weekday using the same action as the Demo menu. This changes local sample groups, not real users.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>JSON.stringify(await advanceDay())}];
 try{for(const tool of tools)await ctx.registerTool(tool);registration='기본 액션 3개 등록됨';}catch{registration='API 등록 불가 · 기본 UI는 정상 작동';}}
async function checkClock(){if(state.demoDate||fatal||busy)return;const now=todaySeoul();if(now>state.today){cancelCutout();try{await dispatch({type:'ADVANCE_DATE',date:now});render();}catch(error){setBanner(storageMessage(error));}}}

try{const saved=loadState();if(saved){state=validateState(saved);if(!state.demoDate&&todaySeoul()>state.today){const next=reduce(state,{type:'ADVANCE_DATE',date:todaySeoul()});saveState(next);state=next;}}}catch(error){fatal=error?.name==='SyntaxError'||String(error?.message).startsWith('invalid state')?'저장된 기록의 형식을 읽지 못했어요. 기존 데이터를 자동으로 지우거나 덮어쓰지 않았어요.':storageMessage(error);}
document.querySelector('#demo-menu').onclick=demoMenu;
document.querySelector('#sheet-close').onclick=closeSheet;
document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkClock();});
window.addEventListener('storage',e=>{if(e.key==='skkugit.demo.v1'||e.key===null){stale=true;setBanner('다른 탭에서 도감이 바뀌었어요. 이 탭을 새로고침한 뒤 이어가 주세요.');}});
setInterval(checkClock,60_000);
render();registerWebMCP();
